### ISSUE TITLE
precision on kitti test set

### ISSUE THREAD

**Issue by Z-Lee-corder** [sankin97/LoGoNet#2]
Thank you for sharing this project！I have a issue to ask you:
I try to train LoGoNet with all KITTI training data for 80 epochs and submit results to KITTI test set. But the precision of car on moderate level is only 82%, I want to know how to achieve 85.06% as paper said?

Is the model configuration on kitti test set different from that on kitti validation set?

If so, what changes need to be made?

**Comment by microjie372** [comment]
Hello, have you solved this problem? I also meet this problem. That is ,when I train model on 3712 training split and obtain performance on 3769 validation split based on one model configuration. While when submitting to KITTI test server, the model configuration useful for validation does not work if I use 100% train +val split.

**Comment by kikiki-cloud** [comment]
Hello, I want to ask, why did my kitti data set report the following errors during training.
Traceback (most recent call last):
  File "detection/tools/train.py", line 204, in <module>
    main()
  File "detection/tools/train.py", line 153, in main
    last_epoch=last_epoch, optim_cfg=cfg.OPTIMIZATION
  File "/home/linux/guorong/qinhao/LoGoNet/utils/al3d_utils/optimize_utils/__init__.py", line 52, in build_scheduler
    optimizer, total_steps, last_step, optim_cfg.LR, list(optim_cfg.MOMS), optim_cfg.DIV_FACTOR, optim_cfg.PCT_START
  File "/home/linux/guorong/qinhao/LoGoNet/utils/al3d_utils/optimize_utils/learning_schedules_fastai.py", line 85, in __init__
    super().__init__(fai_optimizer, total_step, last_step, lr_phases, mom_phases)
  File "/home/linux/guorong/qinhao/LoGoNet/utils/al3d_utils/optimize_utils/learning_schedules_fastai.py", line 45, in __init__
    self.step()
  File "/home/linux/guorong/qinhao/LoGoNet/utils/al3d_utils/optimize_utils/learning_schedules_fastai.py", line 58, in step
    self.update_lr()
  File "/home/linux/guorong/qinhao/LoGoNet/utils/al3d_utils/optimize_utils/learning_schedules_fastai.py", line 51, in update_lr
    self.optimizer.lr = func((step - start) / (end - start))
ZeroDivisionError: division by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3213650) of binary: /home/linux/anaconda3/envs/logonet/bin/python
Traceback (most recent call last):
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/linux/anaconda3/envs/logonet/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
